### ISSUE TITLE
Thunderhead Bident not increasing the push distance in abilities

### ISSUE THREAD

**Issue by jamestfox64** [andyaiken/forgesteel#763]
**Describe the bug**
When adding the Thunderhead Bident to your inventory it correctly increases damage in abilities, but does not increase/add push distance.

**To Reproduce**
1. Create a character that can wield the Thunderhead Bident (Medium weapon)
2. Add Thunderhead Bident to inventory
3. Select the Mains tab and click on an ability card
4. See no addition to forced movement

**Expected behavior**
All tiers should have push distance increased by 1 or add "push 1" if none present

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome version: 143.0.7499.41
 - Version of Forge Steel 12.52.0

**Comment by andyaiken** [comment]
Fixed

**Comment by jamestfox64** [comment]
Which version should it be fixed on? When I opened the site again on
version 14.142.0 it still does not seem to be adding any push distance to
abilities.
